// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, PrismaConfigInternal } from "prisma/config";
import OUTPUTS, { TerraformOutputs } from "./src/lib/terraform_outputs";
import { is_prod } from "./src/lib/server-utils";
import path from "node:path";

let config = defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: is_prod() ? (OUTPUTS as TerraformOutputs).database_url : process.env.DATABASE_URL,
  },
});

export default config;
