name: Deploy Portfolio
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-west-1

      - name: Build and Save Image
        run: |
          docker build -t portfolio .
          docker save portfolio > portfolio.tar

      - name: Upload to S3
        run: |
          aws s3 cp portfolio.tar s3://global-files-wal-aws/deployments/portfolio.tar
